name = "m"                          # Worker name
compatibility_date = "2025-10-24"
main = "worker.js"
account_id = "1c13e1ee57220fb5c5ce493cbc31e598"      # Your Cloudflare account ID
workers_dev = true

