name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Publish Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish
